spring:
  config:
    activate:
      on-profile: real
  profiles:
    group:
      real: real, real-db, oauth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc